[package]
name = "dashmap-test"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
dashmap = "5.5.3"
parking_lot = "0.12.1"
sysinfo = "*"
rand = "*"
